title: "Antonio Alvarez de la Paz"
name: "Antonio Alvarez de la Paz"
email: "ant.adlp1986@gmail.com"
description: "Computational physicist & data scientist — molecular dynamics, NLP/OCR, and scientific software."
url: "https://antadlp.github.io"
baseurl: ""
repository: "antadlp/antadlp.github.io"

# Profile (sidebar) — AcademicPages reads these keys
author:
  name: "Antonio Alvarez de la Paz"
  avatar: "/images/profile.jpg"   # put a square photo here; 600x600 works well
  bio: "Computational physicist & data scientist. I build MD and data pipelines to accelerate research."
  location: "Mexico"
  email: "ant.adlp1986@gmail.com"
  links:
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0001-7316-4186"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/antadlp"
    - label: "CV (PDF)"
      icon: "far fa-file-pdf"
      url: "/files/Antonio_Alvarez_CV.pdf"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/antadlp"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins supported by GitHub Pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Theme options used by academicpages / Minimal Mistakes
# (kept minimal; the forked template already includes styles/layouts)
paginate: 5
permalink: /:categories/:title/

# Collections (leave for future expansion)
collections:
  publications:
    output: true
    permalink: /publications/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single
  - scope:
      path: ""
      type: publications
    values:
      layout: single